package io.ap2.a2a.extension.roles.merchant.subagents;

/**
 * DTO for items generated by the LangChain4j AI service.
 *
 * This is a simple class that LangChain4j can parse, which will then be
 * converted to PaymentItem objects.
 */
public class GeneratedItem {

    private String label;
    private String currency;
    private Double price;

    public GeneratedItem() {
    }

    public GeneratedItem(String label, String currency, Double price) {
        this.label = label;
        this.currency = currency;
        this.price = price;
    }

    public String getLabel() {
        return label;
    }

    public void setLabel(String label) {
        this.label = label;
    }

    public String getCurrency() {
        return currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public Double getPrice() {
        return price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }
}
