package io.ap2.a2a.extension.spec;

import java.util.Map;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import io.a2a.util.Assert;

/**
 * Indicates a user has chosen a payment method & approved a payment request.
 * <p>
 * Specification:
 * https://www.w3.org/TR/payment-request/#paymentresponse-interface
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonIgnoreProperties(ignoreUnknown = true)
public record PaymentResponse(
        /**
         * The unique ID from the original PaymentRequest.
         */
        @JsonProperty("request_id") String requestId,

        /**
         * The payment method chosen by the user.
         */
        @JsonProperty("method_name") String methodName,

        /**
         * A dictionary generated by a payment method that a merchant can use
         * to process a transaction. The contents will depend upon the payment
         * method.
         */
        Map<String, Object> details,

        @JsonProperty("shipping_address") ContactAddress shippingAddress,
        @JsonProperty("shipping_option") PaymentShippingOption shippingOption,
        @JsonProperty("payer_name") String payerName,
        @JsonProperty("payer_email") String payerEmail,
        @JsonProperty("payer_phone") String payerPhone
) {

    public PaymentResponse {
        Assert.checkNotNullParam("requestId", requestId);
        Assert.checkNotNullParam("methodName", methodName);
    }
}
